apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-jquery
  namespace: jquery
spec:
  selector:
    matchLabels:
      app: jquery
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: jquery
    spec:
      containers:
      - name: jquery
        image: 060920346106.dkr.ecr.us-east-2.amazonaws.com/jquery-eks:$BUILD_NUMBER
        ports:
        - containerPort: 80
